config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  devise_for :users

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  # Defines the routes for the Users controller
  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: %i[update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  # Defines the routes for the inventory and inventory_foods controller
  resources :inventories, except: %i[update] do
    resources :inventory_foods, only: %i[new create destroy]
  end 
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, foreign_key: :inventory_id, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :description, length: { maximum: 1000 }

  def compute_missing_foods(recipe)
    shopping_list = []
    recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      inventory_food = inventory_foods.where(food_id: food.id)[0]
      unless inventory_food
        shopping_list << [food.food, "#{recipe_food.quantity} #{food.measurement_unit}",
                          recipe_food.quantity * food.unit_price]
        next
      end
      quantity_needed = recipe_food.quantity - inventory_food.quantity
      quantity_needed = 0 if quantity_needed.negative?
      if inventory_food && quantity_needed != 0
        shopping_list << [food.food, "#{quantity_needed} #{food.measurement_unit}", quantity_needed * food.unit_price]
      end
    end
    shopping_list
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
    @foods = @inventory.inventory_foods.includes(:food)
    @foody = Food.all
    @inventory_food = InventoryFood.new
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = current_user.inventories.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_path, notice: 'Inventory created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    authorize! :destroy, @inventory
    @inventory.destroy!

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory successfully deleted.' }
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_add_food_inventory.html.erb
<div class="modal-contents slide-fwd-center  ">
  <div>
    <span>x</span>
  </div>
  <div  class="form-heading">
    <h2>Add Inventory Food</h2>
    <hr style="margin: 5px auto;">
  </div>

  <div class="form-group add-btn">
    <%= form_with url: inventory_inventory_foods_path(@inventory.id), scope: :inventory_foods do |f| %>
      <div class="field">
        <%= f.select :food_id,@foody.collect { |food| [food.food, food.id] }, { :prompt => 'Choose food'},
         class: "form-select mb-3", required: true %>
      </div>
      
      <div class="field">
        <%= f.number_field :quantity, placeholder: "Quantity (e.g 10, 20 etc)", required: true %>
      </div>
      <div class="actions">
      <%= f.submit "Add inventory food" %>
      </div>
    <% end %>
  </div>
</div>

app/views/inventories/index.html.erb
<section class="container w-100 mx-auto mt-5">
<div class="foods-btn">
  <h2>Inventory List</h2>
  <%= link_to 'Add Inventory', new_inventory_path %>
</div>
<% if @inventories.empty? %>
  <p class="no-food">No inventories added yet. Please use the button above ☝️ to add new inventory</p>
<% else %>
<ul class= "list-unstyled align-items-center d-flex flex-column align-items-center w-75">
<% @inventories.each do |inv| %>
    <%= link_to inventory_path(inv.id), style:"text-decoration: none; color: black" do %>
      <li class="card list-style-none mb-7 w-100 card-outline-warning"
      style= "margin-bottom: 4rem; box-outline: #DD7230;
      box-shadow: 0 5px rgba(93, 64, 55, 0.4), 0 10px rgba(93, 64, 55, 0.3),
              0 15px rgba(93, 64, 55, 0.2), 0 20px rgba(93, 64, 55, 0.1),
              0 25px rgba(93, 64, 55, 0.05),
              -5px 5px 40px rgba(100, 0, 0, 0.4);">
      <div class="card-header fs-4" style= "background-color: #E7E393; ">
          <h4 class="card-title text-muted"><%= inv.name %></h4>
        </div>
        <div class="card-body"  style= "background-color: whitesmoke ">
              <p class="card-text"><%= inv.description %></p>
        </div>
        <div class="card-footer d-flex flex-row-reverse">
              <% if can? :destroy, inv %>
            <%= link_to 'Remove', inv, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
            class: "btn btn-outline-danger", type:"button" %>
          <% else %>
            <%= link_to 'View', inventory_path(inv), class: "btn btn-outline-success", type:"button", style: "width: 5.5rem" %>
          <% end %>
            </div>
    </li>
    <% end %>
    <% end %>
</ul>
<% end %>
</section>

app/views/inventories/new.html.erb
<div  class="form-heading">
  <h2>Add New Inventory</h2>
  <hr style="margin: 5px auto;">
</div>

<div class="form-group">
  <%= form_with(model: @inventory) do |f| %>
    <div class="field">
      <%= f.text_field :name, placeholder: "Inventory Name", autofocus: true %>
    </div>
    <div class="field">
      <%= f.text_field :description, placeholder: "Please input inventory desc" %>
    </div>
    <div class="actions">
      <%= f.submit "Add Inventory" %>
    </div>
  <% end %>
<div>

app/views/inventories/show.html.erb
<div class="foods-btn">
  <h2><%= @inventory.name %></h2>
  <% if can? :destroy, @inventory %>
  <a "Add Food" class= "btn btn-primary btn-floating click_add_food_btn" style= "width: 10vw">Add Food</a>
  <% end %>
</div>
  <div class="w-30 foods-btn">
<% if @foods.empty? %>
<p class="no-food">No food added to the inventory yet. Please use the button above ☝️ to add new food. 
<span > Meanwhile here is the inventory&#39;s description🙂🙂:<br> <%= @inventory.description %></span></p>
<% else %>
<table class="table table-hover table-striped table-bordered">
  <thead class="bg-color">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |f| %>
      <tr>
        <td><%= f.food.food %></td>
        <td><%= f.quantity %></td>
        <td>
        <% if can? :destroy, f %>
          <%= link_to 'Remove', inventory_inventory_food_path(:inventory_id => @inventory.id, :id => f.id), 
          data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
          class: "btn btn-outline-danger w-25", style: "margin-top: 0", type:"button" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<div class='modals'>
  <%= render 'add_food_inventory' %>
</div>

<script>
  document.querySelector('.click_add_food_btn').addEventListener('click', (event) => {
    console.log('click add food');
    document.querySelector('.modals').style.display = 'block'
  })

  document.querySelector('.modal-contents > div:first-of-type > span').addEventListener('click', () => {
    document.querySelector('.modals').style.display = 'none'
  })
</script>