config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  devise_for :users

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  # Defines the routes for the Users controller
  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: %i[update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  # Defines the routes for the inventory and inventory_foods controller
  resources :inventories, except: %i[update] do
    resources :inventory_foods, only: %i[new create destroy]
  end 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :destroy
  accepts_nested_attributes_for :recipe_foods
  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def self.compute_total_amount(recipe)
    total_amount = 0
    recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      total_amount += recipe_food.quantity * food.unit_price
    end
    total_amount
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = current_user.recipes
  end

  def show
    @foods = current_user.foods
    @inventories = Inventory.all
    @recipe = current_user.recipes.includes(:recipe_foods).find(params[:id])
    @recipes = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash.now[:notice] = 'You have updated the recipe status to private'
    else
      @recipe.update(public: true)
      flash.now[:notice] = 'You have updated the recipe status to public'
    end
    # redirect_to recipe_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_add_recipe_food.html.erb
<div class="modal-contents slide-fwd-center  ">
  <div>
    <span>x</span>
  </div>
  <div  class="form-heading">
    <h2>Add Recipe Food</h2>
    <hr style="margin: 5px auto;">
  </div>

  <div class="form-group add-btn">
    <%= form_with url: recipe_recipe_foods_path(params[:id]), scope: :recipe_foods do |f| %>
      <% if @foods.empty? %>
        <p>No foods added yet, please add food and try again.</p>
      <% else %>
        <div class="field">
          <%= f.select :food_id,@foods.collect { |food| [food.food, food.id] }, { :prompt => 'Choose Food'}, class: "form-select", required: true %>
        </div>
        <div class="field">
          <%= f.number_field :quantity, placeholder: "Quantity (e.g 10, 20 etc)", required: true %>
        </div>
        <div class="actions">
          <%= f.submit "Add Quantity" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/_add_shopping_list.html.erb
<div class="modal-contents slide-fwd-center shopping">
  <div>
    <span>x</span>
  </div>
  <div  class="form-heading">
    <h2>Generating Shopping List</h2>
    <hr style="margin: 5px auto;">
  </div>

  <h6 style="margin:30px 0 0 50px">Choose an inventory to use</h6>

  <div class="form-group add-btn">
   
    <%= form_with url: shopping_lists_path, method: :get  do |f| %>
      <div class="field">
       <%= f.select :inventory_id, @inventories.collect { |inventory| [inventory.name, inventory.id] }, :prompt => 'Select an Inventory',
        class: 'form-select', required: true %>
      </div>
      <div class="field">
      <%= f.hidden_field :recipe_id, value: @recipes.id, required: true, class: 'border py-2 px-4 w-80' %>
      </div>
      <div class="actions">
        <%= f.submit "Generate" %>
      </div>
    <% end %>
  <div>
</div>

app/views/recipes/_recipe.html.erb
<div class="form-group">
  <%= form_with model: @recipe, method: :post, local: true do |f| %>
    <div class="field">
      <%= f.text_field :name, required: true, placeholder: "Recipe name" %>
    </div>
    <div class="field">
      <%= f.text_field :cooking_time, placeholder: "Coooking time", required: true%>
    </div>
    <div class="field">
      <%= f.text_field :preparation_time, placeholder: "Preparation time", required: true%>
    </div>
    <div class="field">
      <%= f.text_area :description, required: true, placeholder: "Recipe Description"%>
    </div>
    <div class="actions">
      <%= f.submit "Add Recipe" %>
    </div>
  <% end %>
</div> 

app/views/recipes/index.html.erb
<section class="container w-100 mx-auto mt-5">
<div class="foods-btn">
  <h2>Recipe List</h2>
  <%= link_to 'Add Recipe', new_recipe_path %>
</div>
<% if @recipes.empty? %>
  <p class="no-food">No recipies added yet. Please use the button above ☝️ to add a new recipe</p>
<% else %>
<div> 
  <ul class= "list-unstyled align-items-center d-flex flex-column align-items-center w-75">
    <% @recipes.each do |rec| %>
      <%= link_to recipe_path(rec.id), style:"text-decoration: none; color: black" do %>
        <li class="card list-style-none mb-7 w-100 card-outline-warning"
      style= "margin-bottom: 4rem; box-outline: #DD7230;
      box-shadow: 0 5px rgba(93, 64, 55, 0.4), 0 10px rgba(93, 64, 55, 0.3),
              0 15px rgba(93, 64, 55, 0.2), 0 20px rgba(93, 64, 55, 0.1),
              0 25px rgba(93, 64, 55, 0.05),
              -5px 5px 40px rgba(100, 0, 0, 0.4);">
           <div class="card-header fs-4" style= "background-color: #E7E393; ">
              <h4 class="card-title text-muted"><%= rec.name %></h4>
           </div>
           <div class="card-body"  style= "background-color: whitesmoke ">
           <p class="card-text"><%= rec.description %></p>
            </div>
            <div class="card-footer d-flex flex-row-reverse">
                <% if can? :destroy, rec %>
                <%= link_to 'Remove', rec, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                class: "btn btn-outline-danger", type:"button" %>
              <% end %>
              </div>
      </li>
    <% end %>
    <% end %> 
  </ul>
</div>
<% end %>
</section>

app/views/recipes/new.html.erb
<div  class="form-heading">
  <h2>Create Your Recipe</h2>
  <hr style="margin: 5px auto;">
</div>
<div class="recipe-form">
  <%= render "recipe" %>
</div> 

app/views/recipes/show.html.erb
<div class="container p-2 rounded show-container">
  <div class="my-3 text-center">
    <h2 class><%= @recipe.name%></h2>
  </div>
  <div>
    <div class="split">
      <div class="d-flex justify-content-between p-2">
        <h5> Preparation time: <%= @recipe.preparation_time %> min </h5>
        <div class="public-btn form-check form-switch d-flex flex-row">
          <p> Public: <span> <%= form_with url:recipe_path(@recipe.id), :method => :patch do |f| %>
          <%= f.check_box :public, class:"mx-4 form-check-input", checked: @recipe.public, onchange: "this.form.submit();", style: "background-color: #DD7230;"  %>
           </td>
        <% end %>
        </span></p>
      </div>
      </div>
    </div>
    <div>
      <h5 class="p-2"> Cooking time: <%= @recipe.cooking_time %> min </h5>
    </div>
    <div class="d-flex justify-content-around">
    <div class="w-30 foods-btn">
      <a "Generate shopping list" class= "btn btn-primary btn-floating mx-1 click_btns">Generate shopping list</a>
    </div>
    <div class="foods-btn">
      <a class= "btn btn-primary btn-floating mx-1 click_btn">Add ingredient</a>
    </div>
    </div>
  </div>
</div>
<hr class="divider">
<% if @recipe.recipe_foods.empty? %>
  <p class="no-food">No ingredients added yet. Please use the button above ☝️ to add a new ingredient</p>
<% else %>
<table class="table table-hover table-striped table-bordered">
  <thead class="bg-color">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.each do |recipe| %>
      <tr>
        <td><%= recipe.food.food %></td>
        <td><%= recipe.quantity %><%= recipe.food.measurement_unit %></td>
        <td>$<%= recipe.quantity * recipe.food.unit_price %></td>
        <td>
          <% if can? :destroy, recipe %>
            <%= link_to 'Remove', recipe_recipe_food_path(@recipe.id, recipe.id), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
            class: "btn btn-outline-danger", type:"button" %>
          <% end %>
        </td>
      </tr> 
    <% end %>
  </tbody>
</table>
<% end %>

<div class='recipe-modal modals'>
<%= render 'add_recipe_food' %>
</div>
<div class='shopping-modal modals'>
  <%= render 'add_shopping_list' %>
</div>


<script>
  document.querySelector('.click_btn').addEventListener('click', (event) => {
    console.log('click recipe');
    document.querySelector('.recipe-modal').style.display = 'block'
  })

  document.querySelector('.click_btns').addEventListener('click', (event) => {
    console.log('click shopping');
    document.querySelector('.shopping-modal').style.display = 'block'
  })

  document.querySelectorAll('.modal-contents > div:first-of-type > span').forEach(element => {
    element.addEventListener('click', () => {
    document.querySelector('.recipe-modal').style.display = 'none'
    document.querySelector('.shopping-modal').style.display = 'none'
  })
})
</script>