config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  devise_for :users

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  # Defines the routes for the Users controller
  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: %i[update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  # Defines the routes for the inventory and inventory_foods controller
  resources :inventories, except: %i[update] do
    resources :inventory_foods, only: %i[new create destroy]
  end 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, :all if user.present?
    can :manage, Food, user: user if user.present?
    can :manage, Inventory, user: user if user.present?
    can :manage, InventoryFood, inventory: { user_id: user.id }
    can :manage, Recipe, user: user if user.present?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, foreign_key: :food_id, dependent: :destroy
  has_many :recipe_foods, foreign_key: :food_id, dependent: :destroy
  validates :food, :measurement_unit, :unit_price, presence: true
  validates :unit_price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, foreign_key: :inventory_id, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :description, length: { maximum: 1000 }

  def compute_missing_foods(recipe)
    shopping_list = []
    recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      inventory_food = inventory_foods.where(food_id: food.id)[0]
      unless inventory_food
        shopping_list << [food.food, "#{recipe_food.quantity} #{food.measurement_unit}",
                          recipe_food.quantity * food.unit_price]
        next
      end
      quantity_needed = recipe_food.quantity - inventory_food.quantity
      quantity_needed = 0 if quantity_needed.negative?
      if inventory_food && quantity_needed != 0
        shopping_list << [food.food, "#{quantity_needed} #{food.measurement_unit}", quantity_needed * food.unit_price]
      end
    end
    shopping_list
  end
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :destroy
  accepts_nested_attributes_for :recipe_foods
  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def self.compute_total_amount(recipe)
    total_amount = 0
    recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.food
      total_amount += recipe_food.quantity * food.unit_price
    end
    total_amount
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, foreign_key: :user_id, dependent: :destroy
  has_many :recipes, foreign_key: :user_id, dependent: :destroy
  has_many :inventories, foreign_key: :user_id, dependent: :destroy
  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
    devise_parameter_sanitizer.permit :sign_in, keys: %i[email password]
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    authorize! :destroy, @food
    @food.destroy!

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deleted.' }
    end
  end

  private

  def food_params
    params.require(:food).permit(:food, :measurement_unit, :unit_price)
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @inventories = Inventory.all
  end

  def show
    @inventory = Inventory.find(params[:id])
    @foods = @inventory.inventory_foods.includes(:food)
    @foody = Food.all
    @inventory_food = InventoryFood.new
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = current_user.inventories.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_path, notice: 'Inventory created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    authorize! :destroy, @inventory
    @inventory.destroy!

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory successfully deleted.' }
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = current_user.recipes
  end

  def show
    @foods = current_user.foods
    @inventories = Inventory.all
    @recipe = current_user.recipes.includes(:recipe_foods).find(params[:id])
    @recipes = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully deleted.' }
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.public
      @recipe.update(public: false)
      flash.now[:notice] = 'You have updated the recipe status to private'
    else
      @recipe.update(public: true)
      flash.now[:notice] = 'You have updated the recipe status to public'
    end
    # redirect_to recipe_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shoping_lists_helper.rb
module ShopingListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-visit-control" content="reload">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track" => "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/header' %>
    <% flash.each do |type, msg| %>
      <% if type == 'alert' %>
      <div class="flash-msg alert">
        <%= msg %>
      </div>
      <% else %>
      <div class="flash-msg">
        <%= msg %>
      </div>
      <% end %>

    <% end %>
  <main>
    <%= yield %>
  </main>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-color">
  <div class="container-fluid">
    <%= link_to 'Recipe App', authenticated_root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Foods', foods_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipies', recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Public Recipies', public_recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to 'Inventories', inventories_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <div class="d-flex flex-row">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <h6 class= "text-light" style= "padding: 11px">Welcome, <%= current_user.name %></h6>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path , method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path , class: "nav-link" %>
        </li>
      <% end %>
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_table.html.erb
<tr>
  <td><%= food.food %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.unit_price %></td>
  <td>
  <% if can? :destroy, food %>
    <%= link_to 'Delete Food', food, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
              class: "btn btn-danger", type:"button" %>
  <% end %>
  </td>
</tr>