config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  devise_for :users

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root :to => "foods#index", as: :authenticated_root
      get '/users/sign_out' => 'devise/sessions#destroy'
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end
  
  # Defines the routes for the Users controller
  resources :users, only: [:index]
  resources :foods, except: [:update]
  resources :public_recipes,except: [:update]
  resources :shopping_lists, except: %i[update]

  resources :recipes do
    resources :recipe_foods, only: [:create, :destroy]
  end

  # Defines the routes for the inventory and inventory_foods controller
  resources :inventories, except: %i[update] do
    resources :inventory_foods, only: %i[new create destroy]
  end 
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, foreign_key: :food_id, dependent: :destroy
  has_many :recipe_foods, foreign_key: :food_id, dependent: :destroy
  validates :food, :measurement_unit, :unit_price, presence: true
  validates :unit_price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was created successfully' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    authorize! :destroy, @food
    @food.destroy!

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deleted.' }
    end
  end

  private

  def food_params
    params.require(:food).permit(:food, :measurement_unit, :unit_price)
  end
end

app/views/foods/index.html.erb
<div class="foods-btn">
  <h2>Food List</h2>
  <%= link_to 'Add Food', new_food_path %>
</div>
<% if @foods.empty? %>
  <p class="no-food">No foods added yet. Please use the button above ☝️ to add a new food</p>
<% else %>
<table class="table table-hover table-striped table-bordered">
  <thead class="bg-color">
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement Unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    
      <% @foods.each do |food| %>
        <%= render 'shared/table', food: food %>
      <% end %>
  </tbody>
</table>
<% end %>

app/views/foods/new.html.erb
<div  class="form-heading">
  <h2>Add New Food</h2>
  <hr style="margin: 5px auto;">
</div>

<div class="form-group">
  <%= form_with(model: @food) do |f| %>
    <div class="field">
      <%= f.text_field :food, placeholder: "Food Name", autofocus: true, required: true%>
    </div>
    <div class="field">
      <%= f.text_field :measurement_unit, autocomplete: "measurement_unit", placeholder: "Measurement Unit (e.g grams, kilograms etc)", required: true %>
    </div>
    <div class="field">
      <%= f.text_field :unit_price, placeholder: "Unit Price (e.g 10, 20 etc)", required: true %>
    </div>
    <div class="actions">
      <%= f.submit "Add Food" %>
    </div>
  <% end %>
<div>